### ISSUE TITLE
Can't Use In Vite Without `js` in extension resolutions

### ISSUE THREAD

**Issue by johnnyshankman** [merkletreejs/merkletreejs#92]
```
✓ built in 782ms
[commonjs--resolver] Failed to resolve entry for package "treeify". The package may have incorrect main/module/exports specified in its package.json.
file: /Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/merkletreejs/dist/index.js
error during build:
Error: Failed to resolve entry for package "treeify". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/vite/dist/node/chunks/dep-52909643.js:28725:11)
    at resolvePackageEntry (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/vite/dist/node/chunks/dep-52909643.js:28722:5)
    at tryNodeResolve (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/vite/dist/node/chunks/dep-52909643.js:28453:20)
    at Object.resolveId (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/vite/dist/node/chunks/dep-52909643.js:28212:28)
    at file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
    at async resolveId (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/rollup/dist/es/shared/node-entry.js:24117:26)
    at async ModuleLoader.resolveId (file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/rollup/dist/es/shared/node-entry.js:24531:15)
    at async file:///Users/johnshankman/Documents/manifoldxyz/studio-app-burn-redeem-v2/node_modules/vite/dist/node/chunks/dep-52909643.js:8107:16
    at async Promise.all (index 3)
```

**Comment by johnnyshankman** [comment]
Nothing wrong with my usage. This is copy pasta from another repo that doesn't use vite.

**Comment by johnnyshankman** [comment]
I can import it, but the second I reference `MerkleTree` i throw that error.

**Comment by johnnyshankman** [comment]
Figured it out, if you dont have resolve set to pack down JS files you'll have issues when using this package.

Fix:
```
resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
    extensions: ['.js', '.ts', '.tsx'],
  },
```

Broken:
```
resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
    extensions: ['.ts', '.tsx'],
  },
```
